version: "3"
services:
  db:
    image: postgres:14.1
    container_name: db
    networks:
      - my_network
    ports:
      - 8001:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data


  # api:
  #   build:
  #     dockerfile: api/Dockerfile
  #     context: .
  #   container_name: api
  #   networks:
  #     - my_network
  #   links:
  #     - db:db
  #   ports:
  #     - 80:8000
  #   env_file:
  #     - .env
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - db


  scraper:
    build:
      dockerfile: web-scrap/Dockerfile
      context: .
    container_name: scraper
    networks:
      - my_network
    links:
      - db:db
    ports:
      - 4444:8000
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - db  
  

volumes:
  pgdata:


networks:
  my_network:
    driver: bridge
